AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auction-services

  Sample SAM Template for auction-services
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:
#   All functions
  Authorization:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/authorizers/authorizer.handler
      Policies:    ## why we giving these if we pass in the lambda authorizer function
        - Statement:
            - Effect: Allow
              Action: execute-api:Invoke
              Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*"

  MyAuctionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyCustomAuthorizer
        Authorizers:
          MyCustomAuthorizer:
            FunctionArn: !GetAtt Authorization.Arn

  createAuction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./    # these must refer to package.json because it help to deploy dependency
      Handler: src/handler/createAuction.handler
      Events:
        AuctionApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auction
            Method: post 
            RestApiId: !Ref MyAuctionApi
            # Auth:      don't need it because we add it default in the api gateway
            #   Authorizer: MyCustomAuthorizer
      Policies: 
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: arn:aws:dynamodb:eu-north-1:209479300905:table/AuctionTable              
  getAuctions:
    Type: AWS::Serverless::Function  
    Properties:
      CodeUri: ./
      Handler: src/handler/getAuctions.handler   
      Events:
        AuctionApi:
          Type: Api
          Properties:
            Path: /auctions
            Method: get  
            RestApiId: !Ref MyAuctionApi
            Auth:
              Authorizer: MyCustomAuthorizer
      Policies: 
        - DynamoDBReadPolicy:
            TableName: AuctionTable  
      Environment:
        Variables:
          Table_Name : AuctionTable 
  AuctionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: auction-service-209479300905
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  AuctionBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AuctionBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${AuctionBucket.Arn}/*"

  UploadAuctionImage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handler/uploadAuctionImage.handler    
      Events:
        AuctionApi:
          Type: Api
          Properties:
            Path: /auction/{id}/image
            Method: patch
            RestApiId: !Ref MyAuctionApi
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub "${AuctionBucket.Arn}/*"  
      Environment:
        Variables:
          BucketName: auction-service-209479300905
          Table_Name: AuctionTable             
    
  getAuctionById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handler/getAuction.handler    
      Events:
        AuctionApi:
          Type: Api
          Properties:
            Path: /auction/{id}
            Method: get
            RestApiId: !Ref MyAuctionApi
      Policies: 
        - DynamoDBReadPolicy:
            TableName: AuctionTable
      Environment:
        Variables:
          Table_Name: AuctionTable
  placeBid:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handler/placeBid.handler    
      Events:
        AuctionApi:
          Type: Api
          Properties:
            Path: /auction/{id}/bid
            Method: patch
            RestApiId: !Ref MyAuctionApi
      Policies: 
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:UpdateItem
            Resource: arn:aws:dynamodb:eu-north-1:209479300905:table/AuctionTable 
      Environment:
        Variables:
          Table_Name: AuctionTable
          
  processAuction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handler/processAuction.handler
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)  
      Environment:
        Variables:
          Table_Name : AuctionTable
          QUEUE_URL: https://sqs.eu-north-1.amazonaws.com/209479300905/notification-service-queue
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:GetItem
              Resource: 
                - arn:aws:dynamodb:eu-north-1:209479300905:table/AuctionTable/index/statusAndEndingDate    
                - arn:aws:dynamodb:eu-north-1:209479300905:table/AuctionTable      
  AuctionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AuctionTable
      BillingMode: PAY_PER_REQUEST        
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: endingAt 
          AttributeType: S   
      KeySchema:
        - AttributeName: Id
          KeyType: HASH   
      GlobalSecondaryIndexes:
        - IndexName: statusAndEndingDate
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: endingAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

                 
  
# Outputs:
#   AuctionApi:
#     Description: "API Gateway endpoint URL"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"          

