AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auction-services

  Sample SAM Template for auction-services
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:
  createAuction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./       # these must refer to package.json because it help to deploy dependency
      Handler: src/handler/createAuction.handler
      Events:
        AuctionApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auction
            Method: post 
      Policies: 
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: arn:aws:dynamodb:eu-north-1:209479300905:table/AuctionTable              

  getAuctions:
    Type: AWS::Serverless::Function  
    Properties:
      CodeUri: ./
      Handler: src/handler/getAuctions.handler   
      Events:
        AuctionApi:
          Type: Api
          Properties:
            Path: /auctions
            Method: get  
      Policies: 
        - DynamoDBReadPolicy:
            TableName: AuctionTable  
      Environment:
        Variables:
          Table_Name : AuctionTable      
  AuctionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AuctionTable
      BillingMode: PAY_PER_REQUEST        
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH    
  
   
          

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   AuctionApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   createAuction::
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   createAuctionFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
